### ISSUE TITLE
Incompatibility with newest MKLShim and the update-interop-handles branch

### ISSUE THREAD

**Issue by colleeneb** [CHIP-SPV/H4I-HipSOLVER#12]
It looks like there's some kind of incompatibility between https://github.com/CHIP-SPV/H4I-MKLShim/commit/95af8dd5aed2d59f362cab5a7851b61c905ce231 and the update-interop-handles branch which we need to use to use the newer interop handles.

You can reproduce by checking out the latest from MKLShim (95af8dd5aed2d59f362cab5a7851b61c905ce231) and the latest from the `update-interop-handles` branch for HipSOLVER and building (I can provide more step-by-step how I'm building if that would help):
```
> cat s.cpp 
#include <hipsolver.h>

int main()
{
  hipsolverHandle_t roc_handle;
  hipsolverCreate(&roc_handle);
  hipsolverDestroy(roc_handle);

  return 0;
}
```

# Compile
```
hipcc s.cpp -lhipsolver
```

# Run
```
> ./a.out
Error: Invalid handles
```

Thanks!

**Comment by pvelesko** [comment]
Fixed? @colleeneb
